version: 4.6.0.{build}
os: Visual Studio 2017
environment:
  Major: 4
  Minor: 6
  Revision: 0
configuration: Release
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: minimal
test: off
artifacts:
- path: Build\*.nupkg
deploy:
- provider: Environment
  name: MyGet